### ISSUE TITLE
Feature: Add Typescript declarations

### ISSUE THREAD

**Issue by moberwasserlechner** [EvanHahn/HumanizeDuration.js#108]
Hi,

it would be great to have typescript declarations because it would make it easier to use with Angular2 (Typescript) projects.

https://www.typescriptlang.org/docs/handbook/writing-declaration-files.html

Thanks and BR,
Michael

**Comment by EvanHahn** [comment]
I'm happy to accept a pull request for this, even one that's incomplete!

**Comment by EvanHahn** [comment]
The TypeScript declarations should live in the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped), so I'm going to close this issue.

**Comment by RigoTheDev** [comment]
Added TypeScript type definitions to DefinitelyTyped under `@types/humanize-duration`.

**Comment by isaachinman** [comment]
@EvanHahn Any interest in maintaining types within this repo? That is the more modern approach.

**Comment by EvanHahn** [comment]
Sure, happy to review a pull request. (If you can generate a .d.ts file from the existing JSDoc declarations, that would be ideal.)
