### ISSUE TITLE
Feature: add option for keeping zeros in the output

### ISSUE THREAD

**Issue by nfvs** [EvanHahn/HumanizeDuration.js#110]
Sometimes it may make sense having the output with the same length by keeping zeros.

Eg. `21h 06m 00s` instead of `21h 6m`

**Comment by EvanHahn** [comment]
What do you think the API should look like?

**Comment by nfvs** [comment]
I guess just an option like `{leading_zeros: True}`

**Comment by EvanHahn** [comment]
It seems like the option might need to be numeric, like `{ leadingZeros: 2 }` so that the library knows how many leading zeros to insert. Do you agree?

**Comment by nfvs** [comment]
I'm afraid I don't :-)

There are only 60 seconds in a minute, 60 minutes in an hour and 24hours in a day. I don't see a case where you would ever want more than two digits. Maybe calling it `leading_zeros` is misleading?

**Comment by EvanHahn** [comment]
It might make a little more sense for things like years or milliseconds, where the number of leading zeros isn't necessarily constant. There are some other examples, too, like if you want to humanize the whole string in hours only.

What do you think?

**Comment by EvanHahn** [comment]
What about something more flexible? Perhaps something that'd return
each unit with its number and you could build this functionality
yourself?

**Comment by robodude** [comment]
I'm listing a bunch of humanized times and would love a feature like this in order to keep the columns nice and tidy. 

Maybe a new config option that works similarly to the language/word configuration for creating a language

For instance, I'd create a custom humanizer that could be configured like this:
```
humanizeDuration.humanizer({
  numberRendering: {
    y: x => x,
    mo: x => pad(x, 2, '0'),
    w: x => pad(x, 2, '0'),
    d: x => pad(x, 2, '0'),
    h: x => pad(x, 2, '0'),
    m: x => pad(x, 2, '0'),
    s: x => pad(x, 2, '0'),
    ms: x => pad(x, 3, '0'),
  },
```

The defaults would just return the original

**Comment by EvanHahn** [comment]
This library is in maintenance mode, so I won't be adding new features, sadly. I'm going to close this issue. See #120 for more.

**Comment by nfvs** [comment]
@EvanHahn sorry to hear that, but thanks for your work 🍻
