### ISSUE TITLE
Bulgarian Support

### ISSUE THREAD

**Issue by canerelci** [EvanHahn/HumanizeDuration.js#118]
I tried to create a pull request for Bulgarian support but failed with some reason. Anyway, it's not a big thing, you might add these into languages object:

    bg: {
      y: function (c) { return ['години', 'година', 'години'][getSlavicForm(c)] },
      mo: function (c) { return ['месеца', 'месец', 'месеца'][getSlavicForm(c)] },
      w: function (c) { return ['седмици', 'седмица', 'седмици'][getSlavicForm(c)] },
      d: function (c) { return ['дни', 'ден', 'дни'][getSlavicForm(c)] },
      h: function (c) { return ['часа', 'час', 'часа'][getSlavicForm(c)] },
      m: function (c) { return ['минути', 'минута', 'минути'][getSlavicForm(c)] },
      s: function (c) { return ['секунди', 'секунда', 'секунди'][getSlavicForm(c)] },
      ms: function (c) { return ['милисекунди', 'милисекунда', 'милисекунди'][getSlavicForm(c)] },
      decimal: ','
    },

**Comment by EvanHahn** [comment]
This looks good! Would you be able to add tests? You can see an [example English file here](https://github.com/EvanHahn/HumanizeDuration.js/blob/master/test/definitions/en.csv).

**Comment by EvanHahn** [comment]
@canerelci Any updates?

**Comment by EvanHahn** [comment]
There hasn't been movement on this for about 6 months, so I'm going to close this issue. Feel free to comment if you wish to pick this back up.

**Comment by canerelci** [comment]
Sorry, I totally forgot about this. Let me check what can I do. Would you like me to send a PR?

**Comment by EvanHahn** [comment]
Thanks for your PR! We'll keep talking on #126.
