### ISSUE TITLE
This module is in maintenance mode

### ISSUE THREAD

**Issue by EvanHahn** [EvanHahn/HumanizeDuration.js#120]
I no longer have time to add new features to this module, unfortunately.

If you're interested in taking over the project, please leave an issue here and we can discuss! You can also send an email to <me@evanhahn.com> if you'd prefer.

**Comment by DiegoZoracKy** [comment]
Will you still accept and merge PRs?

**Comment by EvanHahn** [comment]
@DiegoZoracKy Yes for bugfixes and small changes; no for large features.

**Comment by DiegoZoracKy** [comment]
I was thinking about trying to get the language from navigator.language,
and set it as the default language. Is this the kind of features that you
wouldn't be accepting?

**Comment by EvanHahn** [comment]
I don't want this library to depend on the browser, so I don't think I'd accept that change. Happy to add something to the readme to show how to do that, though!

**Comment by DiegoZoracKy** [comment]
Yes, I also thought about. We could also try to get the locale from OS when
running on Node.js.

**Comment by EvanHahn** [comment]
Could you create a new issue so we can move discussion there?

**Comment by DiegoZoracKy** [comment]
Done! #122

**Comment by EvanHahn** [comment]
Closing this issue—I'll maintain it but not add new features.
