### ISSUE TITLE
Lao Language support

### ISSUE THREAD

**Issue by sam-lex** [EvanHahn/HumanizeDuration.js#132]
Hello, thanks for this awesome lib.  
Would you be interested in adding support for Lao language? (p.s.: "milliseconds" seems to be non-existent in Laotian)

```javascript
var languages = {
  lo: {
    y: 'ປີ',
    mo: 'ເດືອນ',
    w: 'ອາທິດ',
    d: 'ມື້',
    h: 'ຊົ່ວໂມງ',
    m: 'ນາທີ',
    s: 'ວິນາທີ',
    ms: function (c) { return 'millisecond' + (c === 1 ? '' : 's') },
    decimal: ','
  }
}
```
Translation credits to: `Malikoun`

Right now I'm just using a custom humanizer with it defined, and works great. I can provide a PR next week or so if you want.

**Comment by EvanHahn** [comment]
A PR would be great!
