### ISSUE TITLE
Example to measure with seconds given as input

### ISSUE THREAD

**Issue by TGM** [EvanHahn/HumanizeDuration.js#136]
Hello,

Can you update the manual with an example of how to measure the time with seconds given as input?

**Comment by EvanHahn** [comment]
Do you mean something like this?

```javascript
const myTimeInSeconds = 123;
humanizeDuration(myTimeInSeconds * 1000);
```

Or something else?

**Comment by EvanHahn** [comment]
@TGM I'm going to close this issue because I haven't heard back, but let me know if you have more questions!
