### ISSUE TITLE
User can't control a precision for floats

### ISSUE THREAD

**Issue by jvorcak** [EvanHahn/HumanizeDuration.js#139]
If I create a custom language and pass a number `8255.28`, it outputs `8s 255.28000000000065ms` which is not wanted.

It happens because of this line
https://github.com/EvanHahn/HumanizeDuration.js/blob/master/humanize-duration.js#L493

```
const humanizer = humanizeDuration.humanizer({
    language: 'shortEn',
    spacer: '',
    delimiter: ' ',
    decimal: '.',
    languages: {
      shortEn: {
        y: function () {
          return 'y'
        },
        mo: function () {
          return 'mo'
        },
        w: function () {
          return 'w'
        },
        d: function () {
          return 'd'
        },
        h: function () {
          return 'h'
        },
        m: function () {
          return 'm'
        },
        s: function () {
          return 's'
        },
        ms: function () {
          return 'ms'
        },
      },
    },
    units: ['y', 'mo', 'w', 'd', 'h', 'm', 's', 'ms'],
  })
```

**Comment by EvanHahn** [comment]
To quote the readme, HumanizeDuration.js "is actively maintained but no new features will be added." This sounds like a new feature, unfortunately.

I realize it's not as powerful as the `maxDecimalPoints` feature you added in #140, but would the `round` option solve this problem?

**Comment by jvorcak** [comment]
Not really. Using `round` is not powerful enough, we're specifically interested in 2 numbers after `,`.

I think that if a library outputs `8s 255.28000000000065ms` for `8255.28` input, it can be considered as a bug. Can you re-consider adding this?

**Comment by EvanHahn** [comment]
Good point—it's arguably a bug.

I'll think about this and get back to you.

**Comment by EvanHahn** [comment]
For future reference, let's discuss this in the PR at #140.
