### ISSUE TITLE
Fix greek translation code

### ISSUE THREAD

**Issue by thiagonuic** [EvanHahn/HumanizeDuration.js#143]
I noticed that the Greek code you are using is `gr`, but for i18n greek uses `el`. The `gr` code is just for the domain names. Perhaps it would be a good idea to keep both to avoid breaking whoever is using the lib at the moment.

Thanks for the lib btw!

**Comment by EvanHahn** [comment]
Good catch! I'll try to fix this soon.

**Comment by EvanHahn** [comment]
This should be fixed in `humanize-duration@3.15.3`. Thanks for your report!
