### ISSUE TITLE
Different value for NULL

### ISSUE THREAD

**Issue by EmilMoe** [EvanHahn/HumanizeDuration.js#144]
It would be a great feature, I think, if `null` would return `None` or similar in different languages? What do you think? You can still get out `0` by simply using `0`.

An example could be:

```
Time spend on task: None
```

**Comment by EvanHahn** [comment]
While potentially useful, this library is in maintenance mode and no new features will be added.

You could solve this with a wrapper function, like so:

```javascript
function myHumanizer(ms, options) {
  if (ms === null) {
    return 'None'
  } else {
    return humanizeDuration(ms, options)
  }
}
```

Hope that helps!
