### ISSUE TITLE
Decimals for units other than seconds

### ISSUE THREAD

**Issue by graemian** [EvanHahn/HumanizeDuration.js#150]
I'd like to have output like "12.4 days" or "6.5 weeks", but I can't figure out how to get this.

I tried { largest: 1, round: false } but it doesn't work. Is this possible?

**Comment by EvanHahn** [comment]
Hmm, that seems like it should work.

I don't have lots of time to maintain this module, unfortunately—any chance you could attempt a pull request?

**Comment by guanzo** [comment]
Running into the same issue. Happy to do a PR, but I want clarity into the problem and the potential solution.

```js
const ms = 1000 * 60 * 60 * 1.5 // 1.5 hours

humanizeDuration(ms, {
    units: ['h', 'm'],
    largest: 1,
})
// Current output: "1 hour"
// Expected output?: "1.5 hours"

humanizeDuration(ms, {
    units: ['h'],
    largest: 1,
})
// Current output: "1.5 hours"
// Expected output: "1.5 hours"
```

Does the first call output a buggy result in your eyes?
Should these 2 calls return the same output?

**Comment by EvanHahn** [comment]
That change seems reasonable to me.

This feels like a bugfix and not a breaking change, but are there any cases where it could arguably be a breaking change? If so, I'm more hesitant to make this change.

**Comment by guanzo** [comment]
> are there any cases where it could arguably be a breaking change?

If there are, then the existing tests are not comprehensive enough to expose breaking changes. I was surprised that all tests passed after my modifications. I'm happy to add tests for the proposed change, but I can't guarantee that there are no potential breaking changes.

The decision is yours.

**Comment by guanzo** [comment]
Understandable. The fact that the existing tests stilled passed after my modifications is worrisome. I don't have the time to discover breaking changes, so it may be better to leave this alone.

**Comment by EvanHahn** [comment]
I admit that this is the kind of thing that makes me not want to maintain this library any more—there is a large matrix of possible options that are hard to test exhaustively. (I'm sure it could be done by a more competent maintainer.) For example, what happens if you throw `round` into the mix here?

I'm inclined to keep things as is. However, if someone wants to fork this library to fix this bug and make some additional changes (like the one in #141), I'd link to that fork.

**Comment by EvanHahn** [comment]
There hasn't been movement on this issue in several months so I'm going to close.

Feel free to let me know if you'd like me to reopen—I don't want to stop important discussion, I just want to clean up old issues.
