### ISSUE TITLE
Lazy language loading / tree-shakable languages loading

### ISSUE THREAD

**Issue by smnbbrv** [EvanHahn/HumanizeDuration.js#151]
Hi @EvanHahn ,

is it possible to load one or a defined set of particular languages only? 

Currently everything is stored in a single object, all functions are located in one file etc.

Do you plan to move the functions to different files with ES6 imports on top?

Or, at least, have the library separated from each language specifics, that every language can be loaded separately.

**Comment by EvanHahn** [comment]
This library is in maintenance mode, so no new features will be added.

However, if you want to fork this project, feel free. I will include links to forks if they're reasonable.
