### ISSUE TITLE
Add a ceil helper to round to the next biggest integer

### ISSUE THREAD

**Issue by anz000** [EvanHahn/HumanizeDuration.js#162]
I'm currently using round like 
`humanizeDuration( 120.1, { units: ['m'] , round: true })` 

Currently it returns 2 mins, I'd want  3 mins using a ceiling function.
How difficult is it to add a `ceil` (similar to round) but that always rounds to the next integer? 

Thanks.

**Comment by EvanHahn** [comment]
That's a good idea, but because this library is in maintenance mode (see the blurb in the readme), I won't be able to add this feature. Going to close this issue for that reason.

I'm happy to endorse a fork that adds this, though!
