### ISSUE TITLE
ko_RK is not recognized as Korean language.

### ISSUE THREAD

**Issue by SynchroM** [EvanHahn/HumanizeDuration.js#163]
"ko_RK" is not recognized as Korean language while "ko" works.
"pt_PT" also works correctly.

**Comment by EvanHahn** [comment]
I am surprised that `pt_PT` works. What is the output of that?

I would not expect `ko_RK` to work, only `ko`.

**Comment by EvanHahn** [comment]
I haven't heard back on this issue in several months so I'm going to close.

Let me know if you would like me to reopen.
