### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jeandat** [EvanHahn/HumanizeDuration.js#166]
After 47 releases, maybe it is time to maintain a changelog?
For instance, on my project I want to update from 3.20.1 to latest version but I have no clue what changed since.

**Comment by EvanHahn** [comment]
This is the changelog: https://github.com/EvanHahn/HumanizeDuration.js/blob/master/HISTORY.md

Is there something I could do to make this more discoverable?

I'm closing this issue but we can still discuss on the closed issue.

**Comment by jeandat** [comment]
Maybe I'm wrong but seems to me the standard is to name it CHANGELOG.md. Could have seen it though, but I was only searching for a CHANGELOG.md file.

**Comment by EvanHahn** [comment]
I don't know of a standard changelog format other than [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), which recommends `CHANGELOG.md` but implies that `HISTORY` is okay too.

I mostly stole the name from how a few popular Node projects, like [Express](https://github.com/expressjs/express/blob/master/History.md), do things.

I'm going to keep things as is for now (some people may be relying on the existing name), but if I get more feedback that it's hard to find, I'll reconsider. Does that sound good?

**Comment by jeandat** [comment]
Yeah sure. I will know next time to look for those names too.
