### ISSUE TITLE
Feature: Duration in the past

### ISSUE THREAD

**Issue by sweitzel** [EvanHahn/HumanizeDuration.js#167]
If I have negative seconds, Humanize could automatically convert it to a Human duration in the past:

humanize(-60) = 1 minute ago

This is the only reason why i currently cannot use Humanize and have to use momentjs :-(

**Comment by EvanHahn** [comment]
This library is actively maintained but no new features will be added, so I'm not going to do this, unfortunately.

However, if a fork of the library adds this, I'm happy to link to it from the readme.
