### ISSUE TITLE
Missing case for Slovenian language

### ISSUE THREAD

**Issue by DanielSWolf** [EvanHahn/HumanizeDuration.js#194]
The code that handles the week unit for the Slovenian language seems to be incomplete: It checks three special cases, but it has no `else` branch for the default case.

Here's the relevant excerpt:

```js
w(c) {
  if (c % 10 === 1) {
    return 'teden';
  } else if (c % 10 === 2 || (Math.floor(c) !== c && c % 100 <= 4)) {
    return 'tedna';
  } else if (c % 10 === 3 || c % 10 === 4) {
    return 'tedne';
  }
},
```

Google Translate translates "100 weeks" as "100 tednov", so the value for the `else` branch should probably be "tednov", but I don't speak Slovenian myself.

**Comment by EvanHahn** [comment]
Thanks for reporting! This should be fixed in `humanize-duration@3.25.1`.
