### ISSUE TITLE
Provide an option to omit the spacing between values and units

### ISSUE THREAD

**Issue by cameronbraid** [EvanHahn/HumanizeDuration.js#197]
When using a `shortEnglishHumanizer` as per your docs, I would like it to render as follows :
```
shortEnglishHumanizer(15600000); // '4h, 20m'
```
instead of 
```
shortEnglishHumanizer(15600000); // '4 h, 20 m'
```

**Comment by EvanHahn** [comment]
You should be able to use the `spacer` option:

```js
humanizeDuration(260040000, { spacer: "" });
```

Hope this helps!

**Comment by cameronbraid** [comment]
Thanks mate.. dunno how I missed that when looking at the docs :)

**Comment by EvanHahn** [comment]
No problem. There are a lot of options!
