### ISSUE TITLE
An API to return the parts of the computed humanized duration

### ISSUE THREAD

**Issue by solimant** [EvanHahn/HumanizeDuration.js#201]
# 🙋 Feature Request
It would be nice if we can have a `humanizeDurationParts` that can return the parts of the computed humanized duration. 

## 🤔 Expected Behavior
`humanizeDurationParts` would return a shaped representation of the humanized duration. For example, something like:
```js
humanizeDurationParts(12000); // {largest: 'second', parts: [{unit: 'second', value: 12}]}
humanizeDurationParts(97320000); // {largest: 'day', parts: [{unit: 'day', value: 1}, {unit: 'hour', value: 3}, {unit: 'minute', value: 2}]}
```
Alternatively, we can discuss what's the best shape to return; for example:
- Array ordered by largest unit:
  ```js
  humanizeDurationParts(70000); // [{unit: 'minute', value: 1}, {unit: 'second', value: 12}]
  ```
- Unordered array (would have to traverse whole array if interested in a particular unit):
  ```js
  humanizeDurationParts(70000); // {largest: 'minute', parts: [{unit: 'second', value: 12}, {unit: 'minute', value: 1}]}
  ```
- Map/Associative array (simple, but can be cumbersome when traversing):
  ```js
  humanizeDurationParts(70000); // {'minute': 1, 'second': 12}
  ```

## 😯 Current Behavior
There is no such API.

## 💁 Possible Solution
Parse the output string of `humanizeDuration`? But what do you do if the output string is in a different language?

## 🔦 Context
Be able to use this with the [`Intl.RelativeTimeFormat` API](https://v8.dev/features/intl-relativetimeformat) so that one can be able to pass the correct unit to the API to render something like `3 months ago`.

## 💻 Examples
```js
const rtf = new Intl.RelativeTimeFormat('en', { numeric: 'auto' });
const {value, unit} = humanizeDurationParts(12000)[0]; // assuming ordered array shape
rtf.format(value, unit); // "in 12 seconds"
```
OR
```js
const rtf = new Intl.RelativeTimeFormat('en', { numeric: 'auto' });
const {value, unit} = humanizeDurationParts(-70000)[0]; // assuming ordered array shape
rtf.format(value, unit) // "1 minute ago"
```

**Comment by EvanHahn** [comment]
Would [the `parse-ms` module work for you](https://github.com/sindresorhus/parse-ms)?

This library is actively maintained but no new features will be added, so I'm going to close this issue, but I'm happy to discuss a fork or help out with another module.

**Comment by solimant** [comment]
> Would [the `parse-ms` module work for you](https://github.com/sindresorhus/parse-ms)?
> 
> This library is actively maintained but no new features will be added, so I'm going to close this issue, but I'm happy to discuss a fork or help out with another module.

Yes, that works, thank you very much!
