### ISSUE TITLE
Hide "number of units" when 1

### ISSUE THREAD

**Issue by PeterKottas** [EvanHahn/HumanizeDuration.js#202]
Apologies if this was asked before, but it's quite vaguely defined and my searches didn't yield results.

Is there a way to achieve:

```
humanizeDuration(3600000); => // 'hour' or 'an hour'
// instead of what it currently returns:
humanizeDuration(3600000); => // '1 hour'
```

This applies to all units, I understand it would require big changes in localization files. Not a big deal, just curious. 

Thanks

**Comment by EvanHahn** [comment]
I don't believe this is possible, unfortunately. Because this library is in maintenance mode, I don't plan to add a feature like this, but I'm happy to endorse a fork or add some documentation if you figure out a way to do this!

**Comment by PeterKottas** [comment]
Fair enough! Thanks for the info.
