### ISSUE TITLE
Feature: Add option to interchange the humanized words from right to left/ Swahili Language optimization 

### ISSUE THREAD

**Issue by BossBele** [EvanHahn/HumanizeDuration.js#207]
As a native Swahili language speaker, I expect the humanized duration to start with words before the count.
Eg: "1 day" in Swahili is "siku 1".

Currently, the format does not adhere to the Swahili language; ie. "1 day" = "1 siku".

To solve this, an option to exchange the position of the word would help. Otherwise, an extended formatting function for Swahili would suffice.

**Comment by BossBele** [comment]
Caveats for implementing an extended formatting function for Swahili means that adding a customized Swahili language humanizer would be impossible:

const humanizer = humanizeDuration.humanizer()

```js
humanizer.languages.shortSW = {
  y: () => 'mw',
  // ...
```

**Comment by EvanHahn** [comment]
This has been fixed in aff718e23022163a2d1369a81b84642d29c7a4b4 and deployed in `humanize-duration@3.27.3`. Thanks for your report!
