### ISSUE TITLE
idea: use browser Intl to avoid embedding strings

### ISSUE THREAD

**Issue by kapouer** [EvanHahn/HumanizeDuration.js#209]
Hi,

The Intl api is quite well supported, and has polyfills (even from polyfill.io).

**Comment by EvanHahn** [comment]
I like this idea but don't plan to make any significant changes to this library.

Would you like to fork it and make this change? I can link to it from the README if so!

**Comment by kapouer** [comment]
Actually I already made something in that direction, though not exactly the same since it outputs relative dates (ago, in, etc..)
https://github.com/kapouer/duration-relativetimeformat

**Comment by EvanHahn** [comment]
Looks interesting!

If you build a version of Humanize Duration that uses `Intl`, let me know and I'll include a link.

I'm going to close this issue for now.
