### ISSUE TITLE
Localize thousand separators

### ISSUE THREAD

**Issue by renoguyon** [EvanHahn/HumanizeDuration.js#211]
It seems that currently there is no way to customize thousand separators.

The feature is on this page but was not implemented: https://github.com/EvanHahn/HumanizeDuration.js/issues/61

In some cases we have values greater than 1000, displayed like `1234` instead of `1,234` in english or `1 234` in french.

**Comment by EvanHahn** [comment]
This library is actively maintained but no new features will be added. I like this feature request but don't plan to add it.

If you'd like to fork and add this feature, feel free! I can link to your code from the readme.
