### ISSUE TITLE
[feature] duration in the past and future

### ISSUE THREAD

**Issue by cmldk** [EvanHahn/HumanizeDuration.js#212]
Can I implement duration in the past as an additional option? @EvanHahn 

I will add an extra option for the feature for both the past and future. While calling the function, the option will be like that:

```
options = {
  ...
  adverb_of_time: true
}
```
Then I will add extra keys for the past and future according to languages as shown below.
```
dictionary = {
  ...
  en: {
    ...
    past: "in %s",
    future: "%s ago"
  }
  ...
}
```

**Comment by cmldk** [comment]
@EvanHahn. Thank you for your response. I completed the feature. You can check the file and commits using the GitHub fork repo [here](https://github.com/cmldk/HumanizeDuration.js).

The example codes below the **timeAdverb** title. Also, I added a code snippet for testing in **test/humanizer.js**

**Comment by EvanHahn** [comment]
Thanks. I'll take a look at this.

**Comment by EvanHahn** [comment]
Added it to the readme in 6afef107949bea4fc6edf5b2b0cd91cbbc646a3c.

Thanks!
