### ISSUE TITLE
Arabic has an issue with dual names

### ISSUE THREAD

**Issue by 6km** [EvanHahn/HumanizeDuration.js#221]
In Arabic, dual names like two weeks, two days, *etc.*, are written without the amount of the unit.
**Arabic is unique among languages for having this grammatical dual form.**

For example, *two weeks* is translated as **أسبوعين**, not **2 أسبوعين**.

I can work on a fix for this.

\
*Thanks for your efforts in humanize-duration!*

**Comment by rasa** [comment]
@6km I am considering a PR or friendly fork that provides the time unit names as abbreviations, so "3h 2m", instead of "3 hours, 2 minutes". Is it possible to provide abbreviations in Arabic, if the digit itself is not included? /cc @tomasz1986

**Comment by 6km** [comment]
@rasa I think it's really good to support time abbreviations in Arabic! Here's a list of them:

- year `->` **ع** stands for "عام"  or  **س** stands for "سنة"
- month `->` **ش** stands for "شهر"
- week `->` **أ** stands for "أسبوع"
- day `->` **ي** stands for "يوم"
- hour `->` **س** stands for "ساعة"
- minute `->` **د** stands for "دقيقة"
- second `->` **ث** stands for "ثانية"

Using abbreviations for time units in Arabic is not as common as it is in English; however, it's possible to use them in contexts where the space is limited.

**Comment by rasa** [comment]
@6km Thank you for the help! I included your feedback in my fork [here](https://github.com/rasa/HumanizeDuration.js/blob/35c5145803b651594d7cc26c9a56ccbe70f07575/humanize-duration.js#L109). It seems the values I had for Arabic were correct, but it's always helpful to have someone review it.

**Comment by 6km** [comment]
@rasa Thanks for including my feedback! I'm so glad to hear that!

**Comment by EvanHahn** [comment]
This was fixed in `humanize-duration@3.32.1`.
