### ISSUE TITLE
how to "access" existing language definitions?

### ISSUE THREAD

**Issue by pseidemann** [EvanHahn/HumanizeDuration.js#226]
I want to override just _some_ of the units of a language.

e.g.
```javascript
humanizeDuration.languages.shortEn = {
  ...humanizeDuration.languages.en,
  h: () => 'h',
  m: () => 'm',
  s: () => 's',
  ms: () => 'ms',
};
```

would it be possible to somehow expose the existing language implementations?

**Comment by EvanHahn** [comment]
Unfortunately, there's no way to do this.

Because this library is in maintenance mode, I don't intend to add any new features, so I'm going to close this issue. I'm happy to endorse a fork that adds this functionality.

**Comment by pseidemann** [comment]
hi @EvanHahn,
it would be just an `export` of an existing variable I assume. but good to know!
