### ISSUE TITLE
Ability to control language settings in options. 

### ISSUE THREAD

**Issue by darknos** [EvanHahn/HumanizeDuration.js#29]
Could you look at this commit for details:

https://github.com/darknos/HumanizeDuration.js/commit/8eaa252c05ac82df164141d8aec23c7237887d09

One line of code change and you can control language without code modifications.

**Comment by EvanHahn** [comment]
You can do what you've proposed pretty easily:

```js
var humanizer = humanizeDuration.humanizer({
  language: "newLanguage",
  languages: {
    newLanguage: {
      year: function(c) { return c + "yrs"; },
      month: function(c) { return c + "mos"; },
      // ...
    }
  }
});
```

Sorry it took so long to get back to you!
