### ISSUE TITLE
1.5 hours converts wrong

### ISSUE THREAD

**Issue by iamalexkempton** [EvanHahn/HumanizeDuration.js#38]
Hi there,

I'm trying to convert 1.5 hours to '1 hour, 30 minutes', and it behaves wrong. See example:

http://plnkr.co/edit/6y1iXae5kBhfM51owSgx?p=preview

1.25 hours converts fine. Any thoughts? 

Cheers,

Alex

**Comment by iamalexkempton** [comment]
Just looked at the source code and seen that this is intentional. Perhaps it may be worth having this is an option to turn on/off?

**Comment by EvanHahn** [comment]
Yes; there's code to do half intervals. What kind of configuration option would you want?

**Comment by polomarcus** [comment]
PR https://github.com/EvanHahn/HumanizeDuration.js/pull/40

**Comment by EvanHahn** [comment]
PR looks good. I'll merge soon.

**Comment by polomarcus** [comment]
No.. you look good! 

Tell me if you want me to change anything.

**Comment by EvanHahn** [comment]
Just merged #40. Going to clean up the readme and then close this.

**Comment by EvanHahn** [comment]
Pushed 2.4.0 with PR #40!
