### ISSUE TITLE
It would be valuable to add a getSupportedLanguages() function

### ISSUE THREAD

**Issue by evilaliv3** [EvanHahn/HumanizeDuration.js#54]
While working on [GlobaLeaks](github.com/globaleaks/GlobaLeaks) and try to solve issue https://github.com/siddii/angular-timer/issues/180 on [angular-timer](github.com/angular-timer) i found that currently HumanizeDuration does not offer any function in order to export the supported languages.

This would significantly simplify the integration with other projects/libraries.

**Comment by EvanHahn** [comment]
Closed by edd66ea97918f14ce5e2ae8a70c5a796ff33ba20.
