### ISSUE TITLE
Evaluate integration of Coveralls in order to track code coverage on commit

### ISSUE THREAD

**Issue by evilaliv3** [EvanHahn/HumanizeDuration.js#56]
It would be valuable to integrate with Coveralls in order to track code coverage on commit.
Here is an example of integration by means of grunt + mocha + grunt-mocha-istanbul
https://github.com/evilaliv3/scrypt-async-js/tree/feature/saucelabs

Here is an example of results of the coverage analysis: https://coveralls.io/r/evilaliv3/scrypt-async-js

**Comment by EvanHahn** [comment]
I think this is a good idea but not something this project is going to take the time to do.
