### ISSUE TITLE
Evaluate integration of Saucelabs in order to test cross-browser compatibility on commit

### ISSUE THREAD

**Issue by evilaliv3** [EvanHahn/HumanizeDuration.js#57]
It would be valuable to integrate with Saucelabs in order to track code coverage on commit.
Here is an example of integration by means of grunt + mocha + grunt-saucelabs
https://github.com/evilaliv3/scrypt-async-js/tree/feature/saucelabs

Here is an example of results of the coverage analysis: https://saucelabs.com/u/evilaliv3

**Comment by EvanHahn** [comment]
I agree that this is valuable, but I don't have time to set this up. I'm going to say that this is a _wontfix_.
