### ISSUE TITLE
Add HTML test page

### ISSUE THREAD

**Issue by EvanHahn** [EvanHahn/HumanizeDuration.js#60]
As mentioned in #59:

> it can be a good help for the tranlsators, if you put a html page on the github, which has a form to enter values, select language, hit a submit button then get test results.

We should built `evanhahn.github.io/humanizeduration.js` that lets you test everything to see how it shows up.

**Comment by brandly** [comment]
made a real simple demo: http://brandly.github.io/humanize-duration-demo/

i didn't fork since i wasn't sure how you'd want the repo. like, maybe you want all that code to live alone on the `gh-pages` branch, or maybe you want it in a `demo/` on `master`. or maybe you hate it

also, what language is `gr`? it's not listed under [supported languages](https://github.com/EvanHahn/HumanizeDuration.js#supported-languages).

**Comment by EvanHahn** [comment]
@brandly I dig this. What if I added you as a collaborator and gave you control of `gh-pages`?

**Comment by brandly** [comment]
i'm down

**Comment by EvanHahn** [comment]
I've added you as a collaborator. `gh-pages` has some stuff on it at the moment—feel free to blow any of it away.

**Comment by brandly** [comment]
do you want docs on that page too? regardless, i'll expose `humanDuration` to `window` so people can have fun in the console

**Comment by EvanHahn** [comment]
I think I'd like a link to the docs at the very least. Totally up to you.

**Comment by brandly** [comment]
i pushed [a demo](https://github.com/EvanHahn/HumanizeDuration.js/commit/07754129eb01a5143c50e9ace00d0829269ae67a). for some reason, it's not showing up for me yet [on github.io](http://evanhahn.github.io/HumanizeDuration.js/), but maybe it will be there once you see this, unless i did something silly

**Comment by EvanHahn** [comment]
This looks great! I'll add a link to this and then we can call this issue closed.

@brandly, would you add yourself to the `contributors` in `package.json` and `bower.json` on `master`?

**Comment by brandly** [comment]
[added myself to contributors](https://github.com/EvanHahn/HumanizeDuration.js/commit/f2b70958f7e4044b0495bb293174202dcfb305df)

**Comment by EvanHahn** [comment]
$$$$$$$$$$$$$$
