### ISSUE TITLE
Return zero if value rounds away to zero

### ISSUE THREAD

**Issue by mkavanagh** [EvanHahn/HumanizeDuration.js#62]
Currently, if you pass `round: true` and the value to be formatted is less than half of the smallest allowed unit, you get an empty string as result:
```
> humanize(500, {round: true});
'0.5 seconds'
> humanize(499, {round: true});
''
```

IMO this makes more sense:
```
> humanize(500, {round: true});
'0.5 seconds'
> humanize(499, {round: true});
'0 seconds'
```

(i.e. if we're on the last unit and we haven't added anything to the result yet, do it regardless of whether the unit count is zero)

**Comment by EvanHahn** [comment]
Good catch—this is a bug.

Related question: right now, there's [a bit of code](https://github.com/EvanHahn/HumanizeDuration.js/blob/master/humanize-duration.js#L253-L255) that returns `"0"` if you pass _exactly_ zero.

```js
humanizeDuration(0)  // => "0"
```

What should happen there?

**Comment by mkavanagh** [comment]
my preference would be to return 0 in the smallest allowed unit in either case - then it still reads as a duration, e.g.
```javascript
humanizeDuration(0, {units: ['day']}); // => "0 days"
```

**Comment by EvanHahn** [comment]
Agreed.

**Comment by TheMcMurder** [comment]
+1
