### ISSUE TITLE
30 seconds instead of 0.5 minutes

### ISSUE THREAD

**Issue by peterbe** [EvanHahn/HumanizeDuration.js#65]
As demonstrated here: http://jsfiddle.net/o3fkjtfL/

The humanize for 30*1000 milliseconds is 0.5 minutes. It looks strange. Especially since the output is, on an incremental counter:
```
...
27 seconds
28 seconds
29 seconds
0.5 minutes
31 seconds
32 seconds
33 seconds
...
```

**Comment by EvanHahn** [comment]
I'm going to remove this in version 3.0.0.
