### ISSUE TITLE
Add a function that will return the localized word for values.

### ISSUE THREAD

**Issue by NKozlov** [EvanHahn/HumanizeDuration.js#68]
Emerging needs, when you need to know only the localized word, not the value. For example, the need has arisen when using the module [angular-timer](https://github.com/siddii/angular-timer).
I am sure that your module is very useful in this way.

**Comment by EvanHahn** [comment]
What is the use case for this? I admit that I'm hesitant to address this.

**Comment by EvanHahn** [comment]
Do you mind if I close this?

**Comment by NKozlov** [comment]
Hello! I'm sorry I took so long to answer, I was on vacation at sea.
There needs when you need to get the word correctly, depending on the time. By adding a function to your library - it will be implemented. Not always have the need to display the time in a format that you offer.

**Comment by EvanHahn** [comment]
Could you offer some sample code that would use this feature?

**Comment by NKozlov** [comment]
See this link: https://github.com/NKozlov/wedding-page/blob/master/resources/javascript/lib/angular-timer.js#L228-L233

**Comment by EvanHahn** [comment]
I will endorse a fork but I do not want to bloat this library with more features. Closing this for now.
