### ISSUE TITLE
Won't Initialize in Strict Mode

### ISSUE THREAD

**Issue by phongmedia** [EvanHahn/HumanizeDuration.js#71]
Hi, I'm running into an issue with this package when it's being built into a javascript file which is declared in `strict mode`. The file it's included in must remain in strict mode, so when I build it this package into the  JS file, or declare `"use strict";` for that matter in the function itself, it gives this error:

`Uncaught TypeError: Cannot set property 'humanizeDuration' of undefined`
`humanize-duration.js:412 Uncaught TypeError: Cannot set property `

The issue is relating to this line on `412`:

```javascript
this.humanizeDuration = humanizeDuration;
```

How could this package be made to work within strict mode? Thanks.

**Comment by phongmedia** [comment]
By changing `this` to `window` fixes it. @EvanHahn What do you think about using `window` rather than `this`? Are there any known drawbacks?

```javascript
window.humanizeDuration = humanizeDuration;
```

**Comment by EvanHahn** [comment]
@phongmedia I believe I fixed this. Could you try [the latest version](https://github.com/EvanHahn/HumanizeDuration.js/blob/c408020463bbe61bbba38ce0fb3da6d37080837e/humanize-duration.js) and make sure the issue is fixed?

**Comment by phongmedia** [comment]
@EvanHahn Great thanks, I see the one you linked there uses `global.`, I'll give that a try, so you can assume it works fine in strict mode unless I message you again. Thanks!

**Comment by EvanHahn** [comment]
@phongmedia Have you tested it? If so, I'll push a new patch version.

**Comment by jakobholmelund** [comment]
It works..

**Comment by EvanHahn** [comment]
Is this all solved?
