### ISSUE TITLE
Make Humanizers option to be able to take a function with current value

### ISSUE THREAD

**Issue by mickeyvip** [EvanHahn/HumanizeDuration.js#74]
Hi and thank you.

I have a situation where I need to decide if to round or not the value based on... the value:

``` javascript
var viewValue = humanizeDuration(x, { round: x > 1000 });
```

I use it in many places so it makes sense to create a `Humanizer` similar to:

``` javascript
var myHumanizer = humanizeDuration.humanizer({
  language: "en",
  round: function(value) {
    return value > 1000;
  }
});
```

**Comment by EvanHahn** [comment]
I'd be hesitant to do this instead of #73. You could solve it with something like this:

```js
humanizeDuration(x, { round: value > 1000 })
```

**Comment by mickeyvip** [comment]
Sorry for the typo in the title.

I am doing what you are proposing (the curly braces got lost, because I copied the example from CoffeeScript), but if I do it in many places, it would be shorter to create 1 `humanazer` and use it instead.

**Comment by EvanHahn** [comment]
Feel free to submit a pull request for this.

**Comment by EvanHahn** [comment]
This library is in maintenance mode, so I won't be adding new features, sadly. I'm going to close this issue. See #120 for more.
