### ISSUE TITLE
Its impossible Uglify

### ISSUE THREAD

**Issue by dangercris** [EvanHahn/HumanizeDuration.js#78]
Hi Dude, your code is awesome and Useful but is impossible minify and concat with another dependencies, can you make it possible?

**Comment by EvanHahn** [comment]
I have been able to minify and concat with no problem. What issues are you seeing?

**Comment by EvanHahn** [comment]
@dangercris What issues were you seeing when minifying?

**Comment by dangercris** [comment]
when I Uglify and Minify you code with angular dependencies and more the i have error with you library got undefined, the solution was Concat and minify with you library at the top of the main file an later other dependencies

**Comment by EvanHahn** [comment]
Could you create a [gist](https://gist.github.com/) that demonstrates your problem?

**Comment by dangercris** [comment]
The diference is in my first file I need put at the top you library and all work like a charm, but when I uglify my main file with your library in different order this got undefined :(
https://gist.github.com/dangercris/0c257f747b0f4e9d40f8

**Comment by EvanHahn** [comment]
What is the error that you see?

**Comment by dangercris** [comment]
Your funciton got Undefinied

**Comment by EvanHahn** [comment]
Could this be because you're using Angular? Take a look at this: <http://stackoverflow.com/a/24659782>

**Comment by EvanHahn** [comment]
@dangercris Any updates on this?

**Comment by jaf0** [comment]
angular.module('myApp').value('HumanizeDuration', HumanizeDuration);

then you can inject it

**Comment by EvanHahn** [comment]
Alright to close this issue?

**Comment by jaf0** [comment]
no connection to the OP, but inactive for 4 months ... be my guest :+1:

**Comment by EvanHahn** [comment]
Closing for now. Feel free to continue discussion or open a new issue.

**Comment by dangercris** [comment]
@EvanHahn the ng-annotate was the solution thanks
