### ISSUE TITLE
AngularJS filter

### ISSUE THREAD

**Issue by sebastianhaas** [EvanHahn/HumanizeDuration.js#80]
Hey! Would you be interested in an AngularJS filter wrapping this library? Or do you rather prefer a separate repository for that?

Thanks!

**Comment by sebastianhaas** [comment]
Btw I already wrote one, really simple. Just a few lines and works great.

**Comment by EvanHahn** [comment]
I'd prefer that in a separate library. I'd be happy to link to it from the readme!

**Comment by sebastianhaas** [comment]
Alright then. I've pushed a first version to bower. Works fine for me.

https://github.com/sebastianhaas/angularjs-humanize-duration

**Comment by EvanHahn** [comment]
Added to the readme in ab5c22cbf19e3257a4af00f294538a0c00dd8dc6. Thanks!
