### ISSUE TITLE
Accept other value instead milliseconds

### ISSUE THREAD

**Issue by NetanelBasal** [EvanHahn/HumanizeDuration.js#81]
I need to humanize number, but I get the number in minutes, and I required to do this:

```js
var input = 6000;
humanizeDuration(input * 60000, { round: true });
```

There is an option to do this native with the plugin?

**Comment by EvanHahn** [comment]
The library doesn't handle this. I don't intend to add this functionality; JavaScript deals with everything in milliseconds.

**Comment by brandly** [comment]
@NetanelBasal you could use the [`milliseconds` module](https://www.npmjs.com/package/milliseconds) to say

```js
humanizeDuration(ms.minutes(input), { round: true });
```
