### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by digitalhobo** [EvanHahn/HumanizeDuration.js#93]
Great module, thanks.

Is their a way to manipulate the font size, so that the number are different sizes to the corresponding result. For example '2 min' would be 2 `<small>min</small>`

Thanks in advance :0)

**Comment by EvanHahn** [comment]
I don't intend to add this feature, but you can do it with the `spacer` and `delimiter` feature.

```javascript
// '1 <small>hour</small>, 30 <small>minutes</small>'
humanizeDuration(5400000, {
  spacer: ' <small>',
  delimiter: '</small>, '
}) + '</small>'
